volumes:
  weddings-data:
    external: true
  pg-admin:
    external: true

services:

  frontend:
    image: node:lts-bullseye
    command: bash -c "npm install --legacy-peer-deps && npm start"
    working_dir: /app
    volumes:
      - ./frontend/ghi/forever-and-always:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_ACCOUNTS_HOST: http://localhost:8010
      WATCHPACK_POLLING: true
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: bossmode@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: bossmode
  postgres:
    image: postgres:14.2-bullseye
    volumes:
      # this helps run initialization scripts
      - ./data/postgres/init:/docker-entrypoint-initdb.d
      # this will hold the data stored by postgres
      - weddings-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=bossmode
    ports:
      - 15432:5432
  accounts:
    build:
      context: ./backend/accounts
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/accounts:/app
    depends_on:
      - postgres
    environment:
      SECRET_KEY: db0a49ab25db171089e1a3950f31f3288df643c7c33ede3f38d6bf7788569e24
      PGHOST: postgres
      DATABASE_URL: postgresql://bossmode:bossmode@postgres:5432/accounts
      PGDATABASE: accounts
      PGUSER: bossmode
      PGPASSWORD: bossmode
