version: "4.1"
services:
  fastapi:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://bossmode:bossmode@db/bossmode
      SIGNING_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
  db:
    build:
      context: ./data
      dockerfile: Dockerfile
    ports:
      - "15432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: bossmode
      POSTGRES_USER: bossmode
      POSTGRES_DB: bossmode
    volumes:
      - weddings-data:/var/lib/postgresql/data
volumes:
  weddings-data:
    external: true
    # pgadmin:
    #     image: dpage/pgadmin4
    #     environment:
    #         - PGADMIN_DEFAULT_EMAIL=bossmode@pgadmin.org
    #         - PGADMIN_DEFAULT_PASSWORD=bossmode
    #     ports:
    #         - '5050:80'
    #     restart: always
    #     volumes:
    #         - pgadmin:/root/.pgadmin
    #         - weddings-data-admin
