version: "4.1"
services:
  fastapi:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://bossmode:bossmode@db/bossmode
      SIGNING_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
  db:
    build:
      context: ./data
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: bossmode
      POSTGRES_USER: bossmode
      POSTGRES_DB: bossmode
    volumes:
      - weddings-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=bossmode@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=bossmode
    ports:
      - '5050:80'
    restart: always
    volumes:
        - pgadmin:/root/.pgadmin
  react-frontend:
    image: node:lts-bullseye
    command: npm start
    working_dir: /forever-and-always
    volumes:
      - ./forever-and-always:/forever-and-always
    environment:
      # look into environment variables to connect front end to backend api
      # environment variable is a reference to something you can use in the frontend
      # give the route to the back end e.g. http:localhost stuff
      # in the front end, reference it either ^ manually or via variable
      - HOST="0.0.0.0"
      - PORT=3100
      - NODE_ENV=development
      - DATABASE_URL="postgresql://bossmode:bossmode@db/bossmode"
    ports:
      - "3100:3100"
volumes:
    weddings-data:
    pgadmin:
    # react-frontend:
