version: "4.1"
services:
  fastapi:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://bossmode:bossmode@db/bossmode
  db:
    build:
      context: ./data
      dockerfile: Dockerfile
    ports:
      - "15432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: bossmode
      POSTGRES_USER: bossmode
      POSTGRES_DB: bossmode
    volumes:
      - weddings-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=bossmode@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=bossmode
    ports:
      - '5050:80'
    restart: always
    volumes: 
        - pgadmin:/root/.pgadmin
  react-frontend:
    build: 
      context: forever-and-always
      dockerfile: Dockerfile.dev
    volumes: 
      - react-frontend:/app/node_modules
      - ./forever-and-always:/forever-and-always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_HOST: http://localhost:8000
      REACT_APP_WS_HOST: ws://localhost:8000
      WAIT_HOSTS: api:3001
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
volumes:
    weddings-data:
    pgadmin:
    react-frontend:
