version: "4.1"
services:
  fastapi:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://weddings:weddings@db/weddings
  db:
    image: postgres
    ports:
      - "15432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: bossmode
      POSTGRES_USER: bossmode
      POSTGRES_DB: bossmode
    volumes:
      - weddings-data:/var/lib/postgresql/data
volumes:
  weddings-data:
