FROM node:18-alpine

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

WORKDIR /app
COPY package.json package.json
RUN npm install
RUN npm install --save styled-components

CMD npm start
